In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris-flower-dataset/IRIS.csv


In [25]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical


In [6]:
iris = pd.read_csv('/kaggle/input/iris-flower-dataset/IRIS.csv')

In [7]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [9]:
iris = load_iris()
X = iris.data
y = iris.target

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [26]:
y_train_one_hot = to_categorical(y_train)
y_test_one_hot = to_categorical(y_test)


In [19]:
model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=4))
model.add(Dense(units=3, activation='softmax'))

In [27]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [28]:
history = model.fit(X_train, y_train_one_hot, epochs=50, batch_size=32, validation_split=0.2, verbose=2)


Epoch 1/50
3/3 - 1s - loss: 0.3692 - accuracy: 0.8646 - val_loss: 0.4001 - val_accuracy: 0.9167 - 775ms/epoch - 258ms/step
Epoch 2/50
3/3 - 0s - loss: 0.3617 - accuracy: 0.8646 - val_loss: 0.3923 - val_accuracy: 0.9167 - 32ms/epoch - 11ms/step
Epoch 3/50
3/3 - 0s - loss: 0.3547 - accuracy: 0.8646 - val_loss: 0.3865 - val_accuracy: 0.9167 - 36ms/epoch - 12ms/step
Epoch 4/50
3/3 - 0s - loss: 0.3482 - accuracy: 0.8646 - val_loss: 0.3811 - val_accuracy: 0.9167 - 33ms/epoch - 11ms/step
Epoch 5/50
3/3 - 0s - loss: 0.3421 - accuracy: 0.8750 - val_loss: 0.3754 - val_accuracy: 0.9167 - 32ms/epoch - 11ms/step
Epoch 6/50
3/3 - 0s - loss: 0.3357 - accuracy: 0.8750 - val_loss: 0.3701 - val_accuracy: 0.9167 - 33ms/epoch - 11ms/step
Epoch 7/50
3/3 - 0s - loss: 0.3303 - accuracy: 0.8958 - val_loss: 0.3651 - val_accuracy: 0.9167 - 33ms/epoch - 11ms/step
Epoch 8/50
3/3 - 0s - loss: 0.3247 - accuracy: 0.8958 - val_loss: 0.3592 - val_accuracy: 0.9167 - 33ms/epoch - 11ms/step
Epoch 9/50
3/3 - 0s - loss: 0.

In [29]:
y_pred = np.argmax(model.predict(X_test), axis=1)


1/1 [==============================] - 0s 53ms/step


In [23]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 90.00%


In [30]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 100.00%


In [31]:
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))


Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [32]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
